name: build-java
description: "Build Java project"
inputs:
  version:
    description: "Java version to use"
    required: false
    default: "17"
  directory:
    description: "App directory"
    required: false
    default: "."
  distribution:
    description: "Java distribution to use"
    required: false
    default: "temurin"

runs:
  using: composite
  steps:
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: ${{ inputs.distribution }}
        java-version: ${{ inputs.version }}
        cache: "gradle"
    - name: Test and Package
      id: gradle-build
      working-directory: ${{ inputs.directory }}
      shell: bash
      run: gradle build
    - name: Upload jar file
      uses: actions/upload-artifact@v3
      with:
        name: "jar-${{github.run_number}}"
        path: "build/libs"
    - name: Upload dockerfile
      uses: actions/upload-artifact@v3
      with:
        name: "docker-${{github.run_number}}"
        path: "Dockerfile"
