name: Build and Deploy

on:
  workflow_call:
    inputs:
      app_name:
        description: 'Application name. Will be used in docker image name'
        required: true
        type: string
      directory:
        description: 'Application location folder'
        required: false
        type: string
        default: "."
#    secrets:
#      dev-repo:
#        required: true
#      dev-k8s-context:
#        required: true
#      prod-repo:
#        required: true
#      prod-k8s-context:
#        required: true
#      gha-pat:
#        required: true

jobs:
  build-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and Test
        id: build-java
        uses: elgunmaqsudzade/actions/build-java@5c9f3aa631439f964266f399025efc2347328725
        with:
          directory: ${{ inputs.directory }}
  deploy_dev:
    needs: [ build-code ]
    runs-on: ubuntu-latest
    steps:
      - name: "Deploy"
        id: deploy
        uses: elgunmaqsudzade/actions/deployer@5c9f3aa631439f964266f399025efc2347328725
        with:
          app_name: ${{ inputs.app_name }}
          directory: ${{ inputs.directory }}
          action_token: ${{ secrets.ACTION_TOKEN }}
#          docker_repo: ${{ secrets.dev-repo }}